export const attributeTypes = {
  Rank: "LOW",
  Weight: "HIGH",
  Height: "HIGH",
  Finishing: "HIGH",
  Championship: "HIGH",
  WinPercentage: "HIGH",
  Mat: "HIGH",
  Runs: "HIGH",
  HS: "HIGH",
  BtAvg: "HIGH",
  Century: "HIGH",
  Wkts: "HIGH",
  BBI: "SPL",
  BwAvg: "LOW",
  Fifers: "HIGH",
  Catch: "HIGH",
  SR: "HIGH",
  Econ: "LOW",
};
